extends "res://scripts/test_week.gd"
func _initialize():
 var s=State.new();s.receive()
 var before=s.data.duplicate(true)
 for q in [counts(),counts(7),counts(-1),{"curb":1},{"curb":1.5,"tide":0,"orbit":0,"signal":0,"rally":0}]:check("bad supplier command inert",not s.order(q,1) and s.data==before)
 s.data.cash=0;before=s.data.duplicate(true);check("unaffordable order preflight",not s.order(counts(1),1) and s.data==before);s.data.cash=55000
 # Legitimate paid 64-copy backroom. No injected inventory or money.
 for day in range(1,4):
  check("capacity fill order",s.order(counts(6,6,6),day));s.receive();s.open();finish(s);s.advance(day)
 check("sixty four copies reserve inbound capacity",s.order(counts(0,0,4),4) and s.backroom_committed()==64)
 s=rt(s,"capacity-inbound");s.receive();s.open();finish(s);s.advance(4)
 before=s.data.duplicate(true);check("full backroom no payment",not s.order(counts(0,0,1),5) and s.data==before)
 s.open();var row=intake(s);offer(s,int(row.floor));var command=State.Used.command(s);before=s.data.duplicate(true)
 check("legitimate full backroom rejects seller",not s.purchase_used(command).ok and s.data==before)
 s.close();check("closing accepted trade cancels no purchase",row.status=="cancelled" and s.data.items.size()==64);row.motion="gone";finish(s)
 # Used acceptance/refusal boundaries and arbitrary labels are real buyer choices.
 s=State.new();day_to(s,2);s.open();row=intake(s);offer(s,100);offer(s,100)
 check("second below-floor offer refuses and cannot third",row.status=="refused" and not offer(s,800).ok and s.data.cash==55000)
 finish(s);s.advance(2);s.open();row=intake(s);s.seller_cancel(row.id,int(row.revision),true)
 check("explicit seller refusal no copy",s.data.items.size()==6 and s.seller().status=="refused")
 finish(s)
 s=State.new();day_to(s,3);s.hire("morgan");s.hire("jules");s.assign("morgan","stocking");s.assign("jules","stocking")
 s.price(2500,"curb");var j=s.claim("morgan","stock","case-01","rack-0001",0)
 check("worker copy slot arbitration",not j.is_empty() and s.claim("jules","stock","case-01","rack-0001",1).is_empty() and s.claim("player","stock","case-02","rack-0001",0).is_empty())
 var t=State.new();var items=s.data.items.duplicate(true)
 check("unfinished claim restore cancels without inventory move",s.save_to("user://claim.json") and t.load_from("user://claim.json") and t.data.items==items and State.Staff.active(t.data).is_empty())
 check("explicit takeover retained receiving prerequisite",not s.take_over("morgan").is_empty() and not s.complete_job("player",Vector2(500,400)) and s.visit_receiving("player",Vector2(370,450)) and s.complete_job("player",Vector2(500,400)))
 s.assign("morgan","checkout");s.assign("jules","checkout");s.open()
 var first=s.buyer_ids()[0];check("over budget reservation uses fixed label",select(s,first) and s.data.customers[first].offer==2500 and s.data.customers[first].budget==2200)
 check("budget refusal returns exact copy and slot",not s.queue(first) and s.data.items["case-01"].location=="shelf" and s.data.items["case-01"].slot_index==0 and s.data.customers[first].decision=="decline")
 s.gone(first);finish(s);check("real wages due despite no sales",s.business_report(3).paid_overhead==2400)
 s.advance(3);s.reprice(2000,"curb");s.open();first=s.buyer_ids()[0];select(s,first);var locked=s.data.customers[first].duplicate(true)
 check("live labels immutable",not s.reprice(100,"curb") and not s.price_copy("case-01",100,s.data.items["case-01"].duplicate(true)) and s.data.customers[first]==locked)
 s.queue(first);s.data.customers[first].settled=true;j=s.claim("morgan","sale","","",-1,first)
 check("FIFO cashier exclusivity",not j.is_empty() and s.claim("jules","sale","","",-1,first).is_empty() and not s.sale(first))
 t=State.new();check("reservation restore intact",s.save_to("user://reserved.json") and t.load_from("user://reserved.json") and t.data.customers[first].offer==2000 and t.data.items["case-01"].owner==first)
 check("restored sale exactly once",not t.claim("jules","sale","","",-1,first).is_empty() and t.complete_job("jules",Vector2(660,500)) and not t.complete_job("jules",Vector2(660,500)) and t.valid())
 # Active buyer cap with eight-day roster; departures must finish before next admission.
 s=State.new();day_to(s,6);s.commit_fixture(cmd(s));s.open();s.tick(200)
 for n in range(3):check("first three admitted",s.arrive(s.buyer_ids()[n]))
 var fourth=s.buyer_ids()[3];before=s.data.duplicate(true);check("fourth admission waits",not s.arrive(fourth) and s.data==before)
 first=s.buyer_ids()[0];s.depart(first);check("leaving still occupies buyer cap",not s.arrive(fourth));s.gone(first);check("departed slot releases admission",s.arrive(fourth))
 # Identity, materialized content and seller terms cannot be tampered after reload.
 s=rt(s,"eight-roster");before=s.data.duplicate(true)
 s.data.daily_content["6"][fourth].budget+=1;check("roster tamper rejected",not s.valid());s.data=before.duplicate(true)
 s.seller().floor+=1;check("seller terms tamper rejected",not s.valid());s.data=before.duplicate(true)
 # Acquisition event ordering chooses an older used copy before later new stock for repeats.
 s=State.new();day_to(s,2);s.open();row=intake(s);offer(s,800);s.purchase_used(State.Used.command(s));finish(s);s.advance(2)
 s.order(counts(1),3);s.receive();var used="used:"+s.data.run_id+":2:1";s.price_copy(used,1600,s.data.items[used].duplicate(true));s.price(2000,"curb")
 # Only these two copies are displayed; starter copies stay in backroom.
 s.stock_copy(used,"rack-0001",0,s.data.layout_revision);s.stock_copy("order-3-curb-1","rack-0001",1,s.data.layout_revision);s.open()
 first=s.buyer_ids()[0];check("new first occurrence skips older used",select(s,first) and s.data.customers[first].item=="order-3-curb-1");serve(s,first)
 var repeat=s.buyer_ids()[3];check("repeat chooses oldest eligible acquisition",select(s,repeat) and s.data.customers[repeat].item==used and s.data.items[used].acquisition_seq<s.data.items["order-3-curb-1"].acquisition_seq)
 serve(s,repeat);check("locked acquisition costs preserved",s.data.sales[0].cost==800 and s.data.sales[1].cost==800 and s.valid())
 # Oldest-copy browse destination must not silently substitute a newer rack.
 s=State.new();day_to(s,6);s.commit_fixture(cmd(s));s.price(2000,"curb")
 s.stock_copy("case-01","rack-0001",0,s.data.layout_revision);s.stock_copy("case-04","rack-0002",0,s.data.layout_revision)
 s.open();s.tick(200);first=s.buyer_ids()[0];check("oldest rack destination",s.arrive(first) and s.data.customers[first].browse_fixture=="rack-0001")
 s.browse(first);check("oldest physical copy selection",s.reserve(first) and s.data.customers[first].copy=="case-01")
 # Save failure/retry and terminal archive regression, isolated files only.
 s=State.new();s.receive();s.checkpoint_path="user://missing-folder/checkpoint.json";s.open();finish(s)
 check("failed checkpoint retains live settlement",s.save_pending and s.data.phase=="report" and s.data.settlements.size()==1)
 s.checkpoint_path="user://retry.json";check("retry does not repeat settlement",s.retry_save() and s.data.settlements.size()==1 and not s.save_pending)
 day_to(s,7);s.open();finish(s);var terminal=s.data.duplicate(true);check("terminal archive before restart",s.restart("user://restart.json"))
 var saved=State.new();check("terminal archive preserved",saved.load_from("user://terminal-"+terminal.run_id+".json") and saved.data==terminal)
 var f=FileAccess.open("res://evidence/week-regressions.json",FileAccess.WRITE);f.store_string(JSON.stringify(results,"  "));f.close()
 print("B6_REGRESSIONS ",results.size());quit(1 if results.any(func(r):return not r.pass) else 0)
