extends SceneTree
const S = preload("res://scripts/systems/engine_proof_state.gd")
var results: Array = []
func check(label: String, ok: bool) -> void:
 results.append({"check":label,"passed":ok})
 print(label, ": ", "PASS" if ok else "FAIL")
func stocked():
 var s = S.new()
 s.setup_new_game()
 s.stock_item("item_000001", "used_wall_shelf_01", "slot_01")
 s.open_store()
 return s
func _init() -> void:
 call_deferred("run")
func run() -> void:
 print("ISOLATED_USER_DIR=",OS.get_user_data_dir())
 var s = stocked()
 check("new_stock_price_locked",not s.price_used_item("item_000009",1.0))
 check("occupied_slot_rejected",not s.stock_item("item_000002","used_wall_shelf_01","slot_01"))
 var a = s.spawn_customer()
 s.customer_browse_and_queue(a)
 s.complete_sale(a)
 check("duplicate_sale_rejected",not s.complete_sale(a) and s.transactions.size()==1)
 check("sale_accounting",is_equal_approx(s.cash,569.99) and is_equal_approx(s.daily_report()["gross_margin"],11.99))
 s = stocked()
 a = s.spawn_customer()
 s.customer_browse_and_queue(a)
 s.close_store()
 check("closed_store_rejects_sale",not s.complete_sale(a))
 s = stocked()
 a = s.spawn_customer()
 var b = s.spawn_customer()
 s.customer_browse_and_queue(a)
 s.customer_browse_and_queue(b)
 check("customers_reserve_distinct_stock",s.customers[a]["selected_item_id"] != s.customers[b]["selected_item_id"] or s.customers[b]["state"] != "queued")
 s = stocked()
 a = s.spawn_customer()
 s.customer_browse_and_queue(a)
 s.pick_up_item("item_000001")
 s.complete_sale(a)
 check("sold_item_not_still_carried",s.carried_item_id == "" or not s.items[s.carried_item_id]["is_sold"])
 var scene = load("res://scenes/main/engine_proof.tscn").instantiate()
 root.add_child(scene)
 await process_frame
 var start = scene.player.position
 Input.action_press("move_forward")
 scene._update_player(0.1)
 Input.action_release("move_forward")
 check("forward_input_moves_toward_camera_forward",scene.player.position.z < start.z)
 scene.state.stock_item("item_000001","used_wall_shelf_01","slot_01")
 scene._handle_open_store()
 await create_timer(3.6).timeout
 check("runtime_customer_reaches_queue",scene.state.customers["customer_0001"]["state"] == "queued")
 scene._handle_interact()
 scene._handle_close_day()
 scene._handle_save()
 scene._handle_load()
 check("scene_handlers_sale_report_reload",scene.state.phase=="report" and scene.state.transactions.size()==1)
 scene.queue_free()
 await process_frame
 var f = FileAccess.open(OS.get_environment("GSS_PROBE_RESULTS"),FileAccess.WRITE)
 f.store_string(JSON.stringify(results,"  "))
 f.close()
 var failed = results.filter(func(x): return not x["passed"]).size()
 print("RECOVERY_PROBES failures=",failed)
 quit(1 if failed else 0)
