## Static route contract for the first-minute screenshot audit artifact.
class_name FirstMinuteAuditRouteContract
extends RefCounted


## Returns ordered first-minute screenshot audit beat specifications.
static func beat_specs() -> Array[Dictionary]:
	return [
		_spec(
			"spawn_start",
			"Spawn/start",
			0,
			"00_spawn_start.png",
			"",
			"spawn_first_look",
			"spawn_orientation",
			"route_start",
			"Talk to Manager",
			"StoreSessionDayOneCustomer/Interactable",
			"store_session",
			"high",
			"store_session",
			"Spawn view shows store identity, HUD, and next counter route."
		),
		_spec(
			"manager_prompt",
			"Manager prompt",
			8,
			"01_manager_prompt.png",
			"manager_prompt",
			"checkout_manager_counter",
			"",
			"",
			"",
			"",
			"training",
			"high",
			"store_session",
			"Manager prompt screenshot proves checkout guidance is active."
		),
		_spec(
			"register_prompt",
			"Register prompt",
			14,
			"02_register_prompt.png",
			"register_prompt",
			"checkout_manager_counter",
			"",
			"",
			"",
			"StoreSessionDayEndTrigger/Interactable",
			"training",
			"high",
			"store_session",
			"Register prompt is active after manager beat."
		),
		_spec(
			"backroom_entry_prompt",
			"Back-room entry or pickup prompt",
			22,
			"03_backroom_entry_or_pickup_prompt.png",
			"backroom_pickup_prompt",
			"stockroom_looking_in",
			"",
			"",
			"",
			"",
			"training",
			"high",
			"store_session",
			"Back-room route exposes the pickup prompt without competing targets."
		),
		_spec(
			"stockroom_work_area",
			"Stockroom work area",
			28,
			"04_stockroom_work_area.png",
			"backroom_pickup_prompt",
			"stockroom_work_area_interior",
			"",
			"",
			"",
			"",
			"environment",
			"normal",
			"visuals",
			"Stockroom screenshot reads as a usable work area."
		),
		_spec(
			"carrying_shelf_transition",
			"Carrying/shelf transition",
			36,
			"05_carrying_shelf_transition.png",
			"training_shelf_transition",
			"shelf_wall_product_focus",
			"",
			"",
			"",
			"",
			"training",
			"high",
			"store_session",
			"Carry HUD and starter shelf target agree after pickup."
		),
		_spec(
			"before_customer_state",
			"Before-customer state",
			45,
			"06_before_customer_state.png",
			"before_customer",
			"product_sale_review",
			"",
			"",
			"",
			"",
			"customer",
			"high",
			"store_session",
			"Shelf stocked state and customer prompt are visible before activation."
		),
		_spec(
			"customer_decision_card",
			"Customer decision card",
			50,
			"07_customer_decision_card.png",
			"customer_decision_card",
			"product_sale_review",
			"",
			"",
			"",
			"",
			"customer",
			"critical",
			"store_session",
			"Decision card is open with route state preserved."
		),
		_spec(
			"result_acknowledgement",
			"Result acknowledgement",
			55,
			"08_result_acknowledgement.png",
			"result_acknowledgement",
			"product_sale_review",
			"",
			"",
			"",
			"",
			"customer",
			"normal",
			"store_session",
			"Result acknowledgement is captured when the route reaches it.",
			false,
			"capture_if_reached"
		),
		_spec(
			"post_customer_recovery",
			"Post-customer recovery",
			58,
			"09_post_customer_recovery.png",
			"post_customer_recovery",
			"product_sale_review",
			"",
			"",
			"",
			"",
			"customer",
			"normal",
			"store_session",
			"Post-customer recovery is captured when the route reaches it.",
			false,
			"capture_if_reached"
		),
		_spec(
			"sixty_second_state",
			"60-second state screenshot",
			60,
			"10_sixty_second_state.png",
			"",
			"product_sale_review",
			"first_minute_boundary",
			"current_route_state",
			"Current active prompt",
			"current_active_target",
			"timebox",
			"high",
			"store_session",
			"A 60-second screenshot records the live state without requiring close day."
		),
	]


static func _spec(
	beat_id: String,
	label: String,
	target_timestamp_sec: int,
	filename: String,
	manual_beat: String,
	visual_row: String,
	expected_stage: String,
	expected_objective: String,
	active_prompt: String,
	interaction_target: String,
	category: String,
	severity: String,
	owner: String,
	acceptance: String,
	required: bool = true,
	reach_policy: String = "required"
) -> Dictionary:
	return {
		"beat_id": beat_id,
		"label": label,
		"target_timestamp_sec": target_timestamp_sec,
		"filename": filename,
		"manual_beat": manual_beat,
		"visual_row": visual_row,
		"expected_stage": expected_stage,
		"expected_objective": expected_objective,
		"active_prompt": active_prompt,
		"interaction_target": interaction_target,
		"category": category,
		"severity": severity,
		"owner": owner,
		"acceptance": acceptance,
		"required": required,
		"reach_policy": reach_policy,
	}
