class_name StoreVisualOverhaulRows
extends RefCounted

const StoreVisualActionContextScript: GDScript = preload(
	"res://game/scripts/store_session/store_visual_action_context.gd"
)
const StoreVisualScopeProfileScript: GDScript = preload(
	"res://game/scripts/store_session/store_visual_scope_profile.gd"
)
const InspirationCloseoutContractScript: GDScript = preload(
	"res://game/scripts/store_session/inspiration_closeout_contract.gd"
)

const FIXTURE_ROOT: String = "VisualSweepOverhaulFixtures"


## Returns the stateful overhaul acceptance rows that sit beside route captures.
static func rows(
	review_target: String,
	hud_context: String,
	camera_fov: float,
	design_checks: Array[String]
) -> Array[Dictionary]:
	return [
		_row(
			9,
			"build_design_tool",
			"Build/design tool",
			"09_build_design_tool.png",
			"build_mode_active",
			Vector3(-1.8, 2.35, 6.25),
			Vector3(-18.0, -18.0, 0.0),
			"%s/BuildDesignTool/PlacementGhost" % FIXTURE_ROOT,
			[
				"ExpandableStoreShell/StarterFloor",
				"%s/BuildDesignTool/Grid" % FIXTURE_ROOT,
				"%s/BuildDesignTool/PlacementGhost" % FIXTURE_ROOT,
				"%s/BuildDesignTool/PlacementFootprint" % FIXTURE_ROOT,
				"%s/BuildDesignTool/BlockedTileMarker" % FIXTURE_ROOT,
				"%s/BuildDesignTool/Toolbar" % FIXTURE_ROOT,
				"checkout_counter",
				"StoreSessionRestockShelf",
			],
			"Place Display Fixture",
			"build_mode_confirm_placement",
			"open floor placement grid",
			"choose a valid floor tile and preview a display fixture before confirming placement",
			"BuildDesignTool/PlacementGhost",
			"build_design",
			"build_grid_hierarchy",
			[
				"editable floor area",
				"placement ghost",
				"blocked placement indicator",
				"confirm and cancel controls",
				"surrounding store context",
			],
			[
				"grid is not visible",
				"placement ghost reads as a placed fixture",
				"toolbar occludes the placement surface",
			],
			["store_construction_and_expansion", "ui_and_sim_feedback"],
			"Original build grid, placement ghost, and compact controls stage Mallcore fixture planning.",
			"Build/design capture validates placement surface hierarchy.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
		_row(
			10,
			"stocked_shelf_state",
			"Stocked shelf state",
			"10_stocked_shelf_state.png",
			"stocked_shelf",
			Vector3(-3.65, 1.58, 2.55),
			Vector3(-4.0, 17.0, 0.0),
			"%s/StockedShelf/ProductFacingA" % FIXTURE_ROOT,
			[
				"StoreSessionRestockShelf",
				"%s/StockedShelf/ProductFacingA" % FIXTURE_ROOT,
				"%s/StockedShelf/ProductFacingB" % FIXTURE_ROOT,
				"%s/StockedShelf/PriceRail" % FIXTURE_ROOT,
				"ExpandableStoreShell/StarterUsedShelfBacker",
			],
			"Review Stocked Shelf",
			"shelf_after_sale_gap",
			"stocked starter display",
			"read product facings, prices, and category grouping before the next sale",
			"StockedShelf/ProductFacingA",
			"shelf_stocked",
			"stocked_shelf_hierarchy",
			["multiple product facings", "price rail", "category grouping", "shelf work surface"],
			["shelf reads empty", "price rail is hidden", "product facings are indistinguishable"],
			["shelf_economics_and_product_readability"],
			"Original fictional game facings and price tags make stocked value readable.",
			"Stocked shelf capture validates the filled display state.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
		_row(
			11,
			"shelf_after_sale_gap",
			"Shelf after-sale gap",
			"11_shelf_after_sale_gap.png",
			"shelf_gap_active",
			Vector3(-3.55, 1.58, 2.15),
			Vector3(-3.0, 18.0, 0.0),
			"%s/ShelfGap/GapMarker" % FIXTURE_ROOT,
			[
				"StoreSessionRestockShelf",
				"%s/ShelfGap/GapMarker" % FIXTURE_ROOT,
				"%s/ShelfGap/LowStockTag" % FIXTURE_ROOT,
				"%s/ShelfGap/RemainingFacingA" % FIXTURE_ROOT,
				"%s/ShelfGap/RemainingFacingB" % FIXTURE_ROOT,
				"StoreSessionBackroomPickup",
			],
			"Restock Shelf Gap",
			"backroom_restock_pickup",
			"starter display gap",
			"notice the sold-down gap and restock the visible shelf pressure point",
			"ShelfGap/GapMarker",
			"shelf_gap",
			"shelf_gap_hierarchy",
			["partially stocked display", "clear missing product gap", "low-stock cue"],
			["shelf reads fully empty", "shelf reads fully stocked", "gap is too subtle"],
			["shelf_economics_and_product_readability"],
			"Original gap markers and remaining facings show restock pressure after a sale.",
			"Shelf-gap capture validates the depleted shelf state.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
		_row(
			12,
			"checkout_transaction_active",
			"Checkout transaction active",
			"12_checkout_transaction_active.png",
			"checkout_transaction_active",
			Vector3(1.9, 1.58, 5.45),
			Vector3(-4.0, -18.0, 0.0),
			"%s/CheckoutTransaction/Surface" % FIXTURE_ROOT,
			[
				"checkout_counter",
				"ExpandableStoreShell/CheckoutRegisterScreen",
				"%s/CheckoutTransaction/Surface" % FIXTURE_ROOT,
				"%s/CheckoutTransaction/ScannedItemSlot" % FIXTURE_ROOT,
				"%s/CheckoutTransaction/PaymentPrompt" % FIXTURE_ROOT,
				"%s/CheckoutTransaction/CustomerAtCheckout" % FIXTURE_ROOT,
			],
			"Ring Up Customer",
			"checkout_transaction_complete",
			"register transaction surface",
			"scan the customer's item and complete payment at the register",
			"CheckoutTransaction/Surface",
			"checkout_transaction",
			"checkout_transaction_hierarchy",
			["customer at service position", "register screen", "scanned item slot", "payment prompt"],
			["transaction reads idle", "customer is missing", "payment step is not findable"],
			["checkout_and_transaction_work", "customers_and_queue"],
			"Original transaction props show payment state without copied terminal UI.",
			"Checkout capture validates active transaction readability.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
		_row(
			13,
			"register_trade_in_no_sale",
			"Trade-in/no-sale register state",
			"13_register_trade_in_no_sale.png",
			"register_trade_in_no_sale",
			Vector3(2.05, 1.58, 5.1),
			Vector3(-4.0, -20.0, 0.0),
			"%s/RegisterDecision/TradeSlip" % FIXTURE_ROOT,
			[
				"checkout_counter",
				"%s/RegisterDecision/TradeSlip" % FIXTURE_ROOT,
				"%s/RegisterDecision/NoSaleStamp" % FIXTURE_ROOT,
				"%s/RegisterDecision/NegativeCashBadge" % FIXTURE_ROOT,
				"ExpandableStoreShell/CheckoutRegisterScreen",
			],
			"Decline Trade-In",
			"queue_waiting_state",
			"register decision surface",
			"review a trade-in offer and decline the no-sale/negative-cash outcome",
			"RegisterDecision/TradeSlip",
			"register_decision",
			"trade_in_no_sale_hierarchy",
			["trade-in slip", "no-sale state", "negative-cash warning", "register context"],
			["state reads like a normal sale", "warning is clipped", "decision surface is hidden"],
			["checkout_and_transaction_work", "ui_and_sim_feedback"],
			"Original trade-in slip and warning language stage a no-sale register state.",
			"Register state capture validates trade-in and negative-cash readability.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
		_row(
			14,
			"customer_queue_state",
			"Customer queue state",
			"14_customer_queue_state.png",
			"queue_waiting",
			Vector3(-0.1, 1.72, 6.7),
			Vector3(-2.0, -8.0, 0.0),
			"%s/CustomerQueue/WaitingCustomerA" % FIXTURE_ROOT,
			[
				"FrontLaneQueue",
				"QueueMarker1",
				"QueueMarker2",
				"%s/CustomerQueue/WaitingCustomerA" % FIXTURE_ROOT,
				"%s/CustomerQueue/WaitingCustomerB" % FIXTURE_ROOT,
				"checkout_counter",
			],
			"Serve Next Customer",
			"checkout_transaction_active",
			"front checkout queue",
			"identify the next waiting customer and move service back to the register",
			"CustomerQueue/WaitingCustomerA",
			"queue_service",
			"queue_lane_hierarchy",
			["two waiting customers", "readable queue order", "service position near checkout"],
			["queue reads as random crowding", "waiting order is unclear", "checkout is hidden"],
			["customers_and_queue", "checkout_and_transaction_work"],
			"Original customer markers and floor order cues make the queue readable.",
			"Queue capture validates occupied waiting-line state.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
		_row(
			15,
			"customization_featured_display",
			"Customization poster and featured display",
			"15_customization_featured_display.png",
			"customization_preview",
			Vector3(-3.05, 1.72, 3.85),
			Vector3(-5.0, 22.0, 0.0),
			"%s/Customization/SelectedFixture" % FIXTURE_ROOT,
			[
				"%s/Customization/SelectedFixture" % FIXTURE_ROOT,
				"%s/Customization/SelectionOutline" % FIXTURE_ROOT,
				"%s/Customization/PosterPreview" % FIXTURE_ROOT,
				"%s/Customization/FeaturedDisplay" % FIXTURE_ROOT,
				"%s/Customization/MaterialSwatches" % FIXTURE_ROOT,
				"StoreSessionRestockShelf",
			],
			"Customize Fixture",
			"customization_apply_preview",
			"selected display fixture",
			"preview poster, featured display, and material changes before applying",
			"Customization/SelectedFixture",
			"customization",
			"customization_selection_hierarchy",
			["selected fixture", "poster preview", "featured display", "material swatches"],
			["selected object is not distinct", "customization UI covers the fixture"],
			["storefront_and_mall_identity", "shelf_economics_and_product_readability"],
			"Original poster and display preview use fictional Mallcore names and colors.",
			"Customization capture validates selected-object and featured-display balance.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
		_row(
			16,
			"stockroom_inventory_state",
			"Stockroom inventory state",
			"16_stockroom_inventory_state.png",
			"stockroom_inventory",
			Vector3(3.15, 1.58, -6.05),
			Vector3(-2.0, -154.0, 0.0),
			"%s/StockroomInventory/InventoryCrate" % FIXTURE_ROOT,
			[
				"StoreSessionBackroomPickup",
				"%s/StockroomInventory/InventoryCrate" % FIXTURE_ROOT,
				"%s/StockroomInventory/CountTags" % FIXTURE_ROOT,
				"%s/StockroomInventory/PickList" % FIXTURE_ROOT,
				"ExpandableStoreShell/StockroomDoorStaffCard",
			],
			"Pull Restock",
			"shelf_gap_restock_pressure",
			"stockroom inventory crate",
			"read backroom counts and pull stock for the floor gap",
			"StockroomInventory/InventoryCrate",
			"stockroom_inventory",
			"stockroom_inventory_hierarchy",
			["inventory crate", "count tags", "pick list", "stockroom work area"],
			["stockroom reads empty", "count tags are hidden", "pickup route is unclear"],
			["shelf_economics_and_product_readability", "store_construction_and_expansion"],
			"Original stockroom crates and count tags communicate inventory without external labels.",
			"Stockroom capture validates inventory work-surface readability.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
		_row(
			17,
			"growth_expansion_preview",
			"Growth expansion preview",
			"17_growth_expansion_preview.png",
			"growth_expansion_preview",
			Vector3(-0.65, 2.2, 4.6),
			Vector3(-17.0, -6.0, 0.0),
			"%s/GrowthExpansion/NewFloorOutline" % FIXTURE_ROOT,
			[
				"ExpandableStoreShell/StarterFloor",
				"%s/GrowthExpansion/NewFloorOutline" % FIXTURE_ROOT,
				"%s/GrowthExpansion/LeaseBoundary" % FIXTURE_ROOT,
				"%s/GrowthExpansion/FixtureCapacityTag" % FIXTURE_ROOT,
				"StoreSessionRestockShelf",
			],
			"Preview Expansion",
			"expansion_confirm",
			"new floor outline",
			"compare current floor capacity with the previewed expansion boundary",
			"GrowthExpansion/NewFloorOutline",
			"growth_expansion",
			"growth_expansion_hierarchy",
			["new floor outline", "lease boundary", "capacity tag", "current store context"],
			["expansion reads like decoration", "boundary clips existing fixtures"],
			["store_construction_and_expansion", "ui_and_sim_feedback"],
			"Original expansion outline and capacity tag show growth without generic editor chrome.",
			"Growth capture validates expansion preview readability.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
		_row(
			18,
			"lighting_balance_review",
			"Lighting balance review",
			"18_lighting_balance_review.png",
			"lighting_balance",
			Vector3(-0.5, 1.65, 5.9),
			Vector3(-3.0, -10.0, 0.0),
			"%s/LightingBalance/LightMeterCard" % FIXTURE_ROOT,
			[
				"FluorescentKeyLight",
				"WarmNeonFill",
				"GreenNeonFill",
				"%s/LightingBalance/LightMeterCard" % FIXTURE_ROOT,
				"checkout_counter",
				"StoreSessionRestockShelf",
			],
			"Adjust Lighting",
			"lighting_apply",
			"lighting balance card",
			"check that key, accent, and work-surface lighting support the sales floor",
			"LightingBalance/LightMeterCard",
			"lighting_balance",
			"lighting_balance_hierarchy",
			["key light", "accent fill", "work-surface visibility", "light meter card"],
			["image is underlit", "accent dominates product read", "meter card clips UI"],
			["storefront_and_mall_identity", "ui_and_sim_feedback"],
			"Original lighting review card ties neon fill to work-surface readability.",
			"Lighting capture validates store identity and surface balance.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
		_row(
			19,
			"decision_panels_work_surface_balance",
			"Decision panels and UI work-surface balance",
			"19_decision_panels_work_surface_balance.png",
			"decision_panels_balance",
			Vector3(1.15, 1.62, 5.75),
			Vector3(-3.0, -14.0, 0.0),
			"%s/DecisionPanels/ActionPanel" % FIXTURE_ROOT,
			[
				"%s/DecisionPanels/ActionPanel" % FIXTURE_ROOT,
				"%s/DecisionPanels/OutcomePanel" % FIXTURE_ROOT,
				"%s/DecisionPanels/CounterClearZone" % FIXTURE_ROOT,
				"checkout_counter",
				"ExpandableStoreShell/CheckoutRegisterScreen",
			],
			"Choose Counter Action",
			"decision_panel_commit",
			"checkout decision panel",
			"choose a register decision while the counter work surface remains visible",
			"DecisionPanels/ActionPanel",
			"decision_panel",
			"decision_panel_surface_balance",
			["action panel", "outcome panel", "counter clear zone", "visible work surface"],
			["panel clips the counter", "UI dominates the work surface", "choice state is ambiguous"],
			["checkout_and_transaction_work", "ui_and_sim_feedback"],
			"Original panel copy and counter clear zone keep UI decisions tied to physical work.",
			"Decision-panel capture validates UI and work-surface balance.",
			review_target,
			hud_context,
			camera_fov,
			design_checks
		),
	]


static func _row(
	index: int,
	name: String,
	label: String,
	filename: String,
	setup_state: String,
	camera: Vector3,
	camera_rotation_degrees: Vector3,
	focus: String,
	anchors: Array[String],
	active_prompt: String,
	next_expected_beat: String,
	next_destination: String,
	local_action: String,
	active_target_suffix: String,
	moment: String,
	surface_role: String,
	must_show: Array[String],
	reject_if: Array[String],
	cluster_ids: Array[String],
	original_adaptation: String,
	pattern_validation: String,
	review_target: String,
	hud_context: String,
	camera_fov: float,
	design_checks: Array[String]
) -> Dictionary:
	var active_target: String = "%s/%s" % [FIXTURE_ROOT, active_target_suffix]
	var actionable_candidates: Array[Dictionary] = [
		StoreVisualActionContextScript.candidate(active_target, "active", ""),
		StoreVisualActionContextScript.candidate(
			"StoreSessionRestockShelf/Interactable",
			"disabled",
			"Store-session shelf action must stay quiet during this review state."
		),
		StoreVisualActionContextScript.candidate(
			"StoreSessionDayEndTrigger/Interactable",
			"disabled",
			"Close-day hotspot must not compete with this review state."
		),
	]
	return {
		"index": index,
		"name": name,
		"label": label,
		"filename": filename,
		"setup_state": setup_state,
		"camera": camera,
		"camera_rotation_degrees": camera_rotation_degrees,
		"camera_fov": camera_fov,
		"focus": focus,
		"anchors": anchors,
		"route_anchor": focus,
		"active_route_stage": name,
		"active_prompt": active_prompt,
		"next_expected_beat": next_expected_beat,
		"next_destination": next_destination,
		"local_action": local_action,
		"route_sequence_index": index - 1,
		"primary_work_surface_target": focus,
		"action_context": StoreVisualActionContextScript.context(
			moment,
			active_target,
			active_prompt,
			local_action,
			next_destination,
			actionable_candidates,
			"normal player view of %s" % label.to_lower()
		),
		"work_surface_review": {
			"surface_role": surface_role,
			"primary_action_surface": focus,
			"dominance_required": true,
			"supporting_props_should_stay_quiet": true,
			"must_show": must_show,
			"reject_if": reject_if,
		},
		"inspiration_closeout": InspirationCloseoutContractScript.closeout_for(
			cluster_ids,
			original_adaptation,
			pattern_validation
		),
		"design_checks": design_checks,
		"scope": "overhaul_acceptance",
		"visual_scope_mode": StoreVisualScopeProfileScript.MODE_AUTHORED_FULL_LABEL,
		"review_target": review_target,
		"hud_context_required": hud_context,
	}
