extends "res://scripts/test_growth.gd"
func _initialize():
 var s=State.new();s.receive()
 check("day1 cannot hire",not s.hire("morgan"))
 day_to(s,3)
 check("hire commits once",s.hire("morgan") and s.hire("morgan") and s.data.wage_commitments.size()==1)
 check("dismiss rehire cannot evade or duplicate",s.dismiss("morgan") and s.hire("morgan") and s.data.wage_commitments.size()==1 and s.valid())
 check("hire Jules and assign",s.hire("jules") and s.assign("morgan","stocking") and s.assign("jules","stocking"))
 for p in State.PRODUCTS:s.price(1000,p)
 var j=s.claim("morgan","stock","case-01","rack-0001",0)
 check("claim no physical mutation",not j.is_empty() and s.data.items["case-01"].location=="backroom" and s.valid())
 check("copy slot contention",s.claim("jules","stock","case-01","rack-0001",1).is_empty() and s.claim("player","stock","case-02","rack-0001",0).is_empty() and not s.stock_copy("case-01","rack-0001",1,0))
 check("no remote or receiving bypass",not s.complete_job("morgan",Vector2(500,400)) and not s.visit_receiving("morgan",Vector2.ZERO))
 check("physical receiving",s.visit_receiving("morgan",Vector2(370,450)))
 var before=s.data.items.duplicate(true)
 check("unfinished save",s.save_to("user://employee-claim.json"))
 var t=State.new();check("restore cancels claims retains inventory wages",t.load_from("user://employee-claim.json") and t.data.items==before and t.data.wage_commitments==s.data.wage_commitments and State.Staff.active(t.data).is_empty() and t.valid())
 check("takeover transfers claim",not s.take_over("morgan").is_empty() and s.claim("morgan","stock","case-01","rack-0001",0).is_empty())
 check("takeover must visit receiving again",not s.complete_job("player",Vector2(500,400)) and s.visit_receiving("player",Vector2(370,450)) and s.complete_job("player",Vector2(500,400)))
 check("completed cannot reverse",s.take_over("morgan").is_empty() and not s.complete_job("player",Vector2(500,400)) and s.data.items["case-01"].location=="shelf")
 j=s.claim("jules","stock","case-02","rack-0001",1)
 check("reassign releases unchanged copy",s.assign("jules","checkout") and State.Staff.job(s.data,"jules").is_empty() and s.data.items["case-02"].location=="backroom")
 s.stock("tide");s.stock("orbit");s.assign("morgan","checkout");s.open()
 for id in s.buyer_ids():s.tick(10);s.arrive(id);s.browse(id);s.reserve(id);s.queue(id)
 s.data.customers[s.data.queue[0]].settled=true
 var head=s.data.queue[0];j=s.claim("morgan","sale","","",-1,head)
 check("cashier and FIFO exclusive",not j.is_empty() and s.claim("jules","sale","","",-1,head).is_empty() and not s.sale(head) and s.claim("player","sale","","",-1,s.data.queue[1]).is_empty())
 before=s.data.items.duplicate(true)
 check("reserved checkout restoration",s.save_to("user://employee-checkout.json") and t.load_from("user://employee-checkout.json") and t.data.items==before and t.data.queue==s.data.queue and t.valid())
 check("no remote sale",not s.complete_job("morgan",Vector2.ZERO))
 check("sale exactly once",s.complete_job("morgan",Vector2(660,500)) and not s.complete_job("morgan",Vector2(660,500)) and s.data.sales.size()==1)
 finish(s);check("real wages report",s.valid() and s.business_report(3).paid_overhead==2400 and s.data.settlements.size()==3)
 s.advance(3);check("next prep no commitment",s.data.wage_commitments.size()==2 and s.dismiss("morgan"))
 s.open();check("returning staff commit on open",s.data.wage_commitments.size()==3 and s.valid() and not s.open());finish(s)
 check("remaining staff paid once",s.business_report(4).paid_overhead==1200 and s.valid())
 s=rt(s,"employee-next-day")
 var stock=State.new();day_to(stock,3);stock.hire("morgan");stock.assign("morgan","stocking");stock.price(1000)
 stock.claim("morgan","stock","case-01","rack-0001",0);stock.open();stock.close()
 check("close releases stock and forbids new",State.Staff.active(stock.data).is_empty() and stock.claim("morgan","stock","case-01","rack-0001",0).is_empty() and stock.data.items["case-01"].location=="backroom")
 check("close settles idle wages",stock.finalize() and stock.valid() and stock.business_report(3).paid_overhead==1200)
 for kind in ["role","employment","wage","job","namespace"]:
  var bad=s.data.duplicate(true)
  match kind:
   "role":bad.staff.jules.role="wizard"
   "employment":bad.employment.clear()
   "wage":bad.wage_commitments.clear()
   "job":bad.jobs[0].actor="unknown"
   "namespace":bad.version=7
  var f=FileAccess.open("user://bad-employee.json",FileAccess.WRITE);f.store_string(JSON.stringify(bad));f.close()
  var prior=t.data.duplicate(true)
  check("reject malformed "+kind,not t.load_from("user://bad-employee.json") and t.data==prior)
 var out=FileAccess.open("res://evidence/employees-state.json",FileAccess.WRITE);out.store_string(JSON.stringify({"checks":results,"employment_result":s.data},"  "));out.close()
 print("B4_EMPLOYEES ",results.size()," checks")
 quit(0 if results.all(func(r):return r.pass) else 1)
